### ISSUE TITLE
rtsp stream

### ISSUE THREAD

**Issue by Pablo-163** [zmwangx/rust-ffmpeg#21]
Hello. I want to receive rtsp stream and decode it. And I can't find some info. Has this library commands for changing delay-time and buffer?

**Comment by zmwangx** [comment]
See the list of available options at https://ffmpeg.org/ffmpeg-all.html#rtsp. As the docs point out, the options can be passed into `avformat_open_input`, which corresponds to [`ffmpeg_next::format::open_with`](https://docs.rs/ffmpeg-next/4.3.3/ffmpeg_next/format/fn.open_with.html) (see `options` argument). I don't know if there are specific options suiting your needs because I don't do rtsp. That's firmly in FFmpeg land and isn't something this library can influence.

I do need to be clear though, this is an issue tracker, not a Q&A forum, and I don't have a lot of time for this project to begin with, so in the future I'll probably just close generic questions like this without answer. Better resources:

- FFmpeg user-facing docs: https://ffmpeg.org/ffmpeg-all.html#rtsp
- FFmpeg Doxygen: https://ffmpeg.org/doxygen/4.1/index.html a bit outdated for whatever reason, but fine for most purposes;
- https://docs.rs/ffmpeg-next/ Not well-documented, I know, but I don't have the time for documentation improvement.

**Comment by Pablo-163** [comment]
Well. I found the answer. It really requires other input. It need ```input_with_dictionary()```. But before that need to set up the "Dictionary" like that:
```let mut name_of_Dictionary = ::ffmpeg::Dictionary::new();
    name_of_Dictionary.set("key", "value");
```
I hope someone will find it helpful.
