### ISSUE TITLE
Filter FPS always drops the very last frame

### ISSUE THREAD

**Issue by CL-Jeremy** [zmwangx/rust-ffmpeg#23]
FFmpeg version: 4.2.3 (Homebrew)

Probably I shouldn't submit this issue since I'm using a fork... but I'm facing this strange issue and I suspect the situation be the same either way.

I'm implementing filtering with the FPS filter on the famed Gifski GIF converter. It's would enable more flexible configurations and potentially more features for preprocessing.
 
My implementation: https://github.com/CL-Jeremy/gifski/commit/cb90a2fb571f6079c1f54dbc52a17ea2340330d3

The result looks fine. However, the FPS filter mysteriously drops the very first frame from the input stream, making the output shorter by one frame each time.

However, as far as I could tell, it's actually the very last frame that gets trimmed out of the sequence.

I have tried using the `eof_action` option and it doesn't help. How can I solve this problem elegantly? Thanks in advance.

**Comment by zmwangx** [comment]
Since I don’t actually have a ton of time to investigate a potential problem (i.e. a potential non-problem), it would be best if you could distill your implementation down to a simple reproducible example that’s not intertwined with `gifski::Collector`, `BinResult`, etc. Then I could take a look.

**Comment by CL-Jeremy** [comment]
Here you are: https://gist.github.com/CL-Jeremy/8a56e19c075443b6a3c15889490f7701
Each time a frame is dropped. I added the flush part and the result is the same.
You can get a GIF and run this program over it several times, i. e. feed in the file, feed in the output from last time, feed in new output from second run, etc., and see how the time becomes shorter each time.

**Comment by zmwangx** [comment]
You're right. So I generated this simple gif at 10 fps looping from 1 to 10 using ImageMagick:

![input](https://user-images.githubusercontent.com/4149852/89126382-d738a800-d517-11ea-9524-2f87ac8cf75c.gif)

Using FFmpeg on the command line:

```console
$ ffmpeg -y -i input.gif -filter:v fps=fps=25.0,format=bgr8 output.gif
```

we get a gif with 25 frames:

```console
$ identify output.gif
output.gif[0] GIF 100x50 100x50+0+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[1] GIF 23x36 100x50+38+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[2] GIF 22x35 100x50+39+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[3] GIF 24x37 100x50+37+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[4] GIF 22x37 100x50+39+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[5] GIF 25x38 100x50+36+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[6] GIF 22x38 100x50+39+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[7] GIF 5x5 100x50+55+5 8-bit sRGB 256c 0.000u 0:00.001
output.gif[8] GIF 26x38 100x50+36+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[9] GIF 17x34 100x50+45+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[10] GIF 25x37 100x50+37+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[11] GIF 22x37 100x50+40+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[12] GIF 1x4 100x50+57+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[13] GIF 25x38 100x50+37+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[14] GIF 18x37 100x50+42+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[15] GIF 25x38 100x50+37+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[16] GIF 23x36 100x50+39+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[17] GIF 1x1 100x50+99+49 8-bit sRGB 256c 0.000u 0:00.001
output.gif[18] GIF 24x38 100x50+38+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[19] GIF 22x37 100x50+39+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[20] GIF 23x38 100x50+38+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[21] GIF 20x21 100x50+41+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[22] GIF 3x10 100x50+58+8 8-bit sRGB 256c 0.000u 0:00.001
output.gif[23] GIF 58x38 100x50+21+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[24] GIF 55x37 100x50+24+1 8-bit sRGB 256c 5962B 0.000u 0:00.001
```

Using your sample program, on the other hand, we get a gif with 22 frames:

```console
$ identify output.gif
output.gif[0] GIF 100x50 100x50+0+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[1] GIF 23x36 100x50+38+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[2] GIF 22x35 100x50+39+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[3] GIF 24x37 100x50+37+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[4] GIF 22x37 100x50+39+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[5] GIF 25x38 100x50+36+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[6] GIF 22x38 100x50+39+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[7] GIF 5x5 100x50+55+5 8-bit sRGB 256c 0.000u 0:00.001
output.gif[8] GIF 26x38 100x50+36+0 8-bit sRGB 256c 0.000u 0:00.001
output.gif[9] GIF 17x34 100x50+45+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[10] GIF 25x37 100x50+37+1 8-bit sRGB 256c 0.000u 0:00.001
output.gif[11] GIF 22x37 100x50+40+1 8-bit sRGB 256c 0.000u 0:00.000
output.gif[12] GIF 1x4 100x50+57+1 8-bit sRGB 256c 0.000u 0:00.000
output.gif[13] GIF 25x38 100x50+37+0 8-bit sRGB 256c 0.000u 0:00.000
output.gif[14] GIF 18x37 100x50+42+0 8-bit sRGB 256c 0.000u 0:00.000
output.gif[15] GIF 25x38 100x50+37+0 8-bit sRGB 256c 0.000u 0:00.000
output.gif[16] GIF 23x36 100x50+39+1 8-bit sRGB 256c 0.000u 0:00.000
output.gif[17] GIF 1x1 100x50+99+49 8-bit sRGB 256c 0.000u 0:00.000
output.gif[18] GIF 24x38 100x50+38+0 8-bit sRGB 256c 0.000u 0:00.000
output.gif[19] GIF 22x37 100x50+39+0 8-bit sRGB 256c 0.000u 0:00.000
output.gif[20] GIF 23x38 100x50+38+0 8-bit sRGB 256c 0.000u 0:00.000
output.gif[21] GIF 20x21 100x50+41+0 8-bit sRGB 256c 5156B 0.000u 0:00.000
```

Ignoring the last column, the difference is exactly the last three frames:

```diff
 output.gif[18] GIF 24x38 100x50+38+0 8-bit sRGB 256c 0.000u
 output.gif[19] GIF 22x37 100x50+39+0 8-bit sRGB 256c 0.000u
 output.gif[20] GIF 23x38 100x50+38+0 8-bit sRGB 256c 0.000u
-output.gif[21] GIF 20x21 100x50+41+0 8-bit sRGB 256c 5156B
+output.gif[21] GIF 20x21 100x50+41+0 8-bit sRGB 256c 0.000u
+output.gif[22] GIF 3x10 100x50+58+8 8-bit sRGB 256c 0.000u
+output.gif[23] GIF 58x38 100x50+21+0 8-bit sRGB 256c 0.000u
+output.gif[24] GIF 55x37 100x50+24+1 8-bit sRGB 256c 5962B
```

and with a cursory look I can't spot a problem in the program, except maybe the lack of an `encoder.flush` at the end which doesn't actually do anything in this case.

I don't have more time today, will try to take a deeper look tomorrow.

**Comment by zmwangx** [comment]
I managed to fix this through meticulously tracing none other than [`ffmpeg.c`](https://github.com/FFmpeg/FFmpeg/blob/n4.3.1/fftools/ffmpeg.c). Note that even the official [`transcoding.c` example](https://github.com/FFmpeg/FFmpeg/blob/n4.3.1/doc/examples/transcoding.c) (though a bit dated) has this exact problem when you replace `filter_spec = "null";` with `filter_spec = "fps=fps=25.0,format=bgr8";`, so it's indeed subtle. (I'll try to mail the ffmpeg-dev mailing list to have the example fixed if I have the time.)

The debug process and fix led me to add some new APIs and realize that several existing APIs are either deprecated or slightly incorrect, so this turned out to be a pretty useful issue; you have my gratitude.

The fixed script (only works against the current master): https://gist.github.com/zmwangx/bacd12df8b8dce4c91db47a34a637004/4ffd2f9a701ceb9e54e45d2f4162e18b2200b979

The script is pretty heavily refactored and reformatted, so it's pretty hard to see the changes, but I've clearly marked where the major behavioral changes occur; reverting those would effectively bring back your original version.

## Explanations

The most useful thing in my debugging process was cranking FFmpeg log level to `trace` (or `debug`). Continuing my example above, on the command line:

```
ffmpeg -loglevel repeat+trace -y -i input.gif -filter:v fps=fps=25.0,format=bgr8 output.gif
```

I had to add a `util::log` API to this crate, but once done I can use the same logging level and compare. The issue becomes rather apparent when we compare the logs:

FFmpeg:

```
...
[Parsed_fps_0 @ 0x7fab28504640] Read frame with in pts 90, out pts 23
[Parsed_fps_0 @ 0x7fab28504640] Writing frame with pts 20 to pts 20
[Parsed_fps_0 @ 0x7fab28504640] Writing frame with pts 20 to pts 21
[Parsed_fps_0 @ 0x7fab28504640] Writing frame with pts 20 to pts 22
[Parsed_fps_0 @ 0x7fab28504640] Duplicated frame with pts 20 2 times
[gif @ 0x7fab28817c00] 23x38 image at pos (38;0) [area:100x50]
[gif @ 0x7fab28817c00] 20x21 image at pos (41;0) [area:100x50]
[gif @ 0x7fab28817c00] 3x10 image at pos (58;8) [area:100x50]
[Parsed_fps_0 @ 0x7fab28504640] EOF is at pts 25
[Parsed_fps_0 @ 0x7fab28504640] Writing frame with pts 23 to pts 23
[Parsed_fps_0 @ 0x7fab28504640] Writing frame with pts 23 to pts 24
[Parsed_fps_0 @ 0x7fab28504640] Duplicated frame with pts 23 1 times
[gif @ 0x7fab28817c00] 58x38 image at pos (21;0) [area:100x50]
[gif @ 0x7fab28817c00] 55x37 image at pos (24;1) [area:100x50]
[out_0_0 @ 0x7fab2842f400] EOF on sink link out_0_0:default.
...
[Parsed_fps_0 @ 0x7fab28504640] 10 frames in, 25 frames out; 0 frames dropped, 15 frames duplicated.
...
```

Sample program, prior to the fixes:

```
...
[Parsed_fps_0 @ 0x7fd04ee04800] Read frame with in pts 90, out pts 23
[Parsed_fps_0 @ 0x7fd04ee04800] Writing frame with pts 20 to pts 20
[gif @ 0x7fd04f01a600] 23x38 image at pos (38;0) [area:100x50]
[Parsed_fps_0 @ 0x7fd04ee04800] Writing frame with pts 20 to pts 21
[gif @ 0x7fd04f01a600] 20x21 image at pos (41;0) [area:100x50]
[Parsed_fps_0 @ 0x7fd04ee04800] Writing frame with pts 20 to pts 22
[gif @ 0x7fd04f01a600] 3x10 image at pos (58;8) [area:100x50]
[Parsed_fps_0 @ 0x7fd04ee04800] Duplicated frame with pts 20 2 times
[Parsed_fps_0 @ 0x7fd04ee04800] EOF is at pts 23
[Parsed_fps_0 @ 0x7fd04ee04800] Dropping frame with pts 23
...
[Parsed_fps_0 @ 0x7fd04ee04800] 10 frames in, 23 frames out; 1 frames dropped, 14 frames duplicated.
...
```

Note the difference of `EOF is at pts 23` vs `EOF is at pts 25`, and the two missing frames. (Previously I observed that the sample program only writes 22 frames, but that's because you forgot to call `write_trailer` on the output context, making the last output frame lost in the buffer.)

As I said I meticulously traced `ffmpeg.c`, which led me to the key realization: **FFmpeg uses `av_buffersrc_close` in [`ifilter_send_eof`](https://github.com/FFmpeg/FFmpeg/blob/6b6b9e593dd4d3aaf75f48d40a13ef03bdef9fdb/fftools/ffmpeg.c#L2183-L2204), instead of sending a `NULL` frame through `av_buffersrc_add_frame` to signal EOF, like we did.** Here's the docs for `av_buffersrc_close`:

```c
/**
 * Close the buffer source after EOF.
 *
 * This is similar to passing NULL to av_buffersrc_add_frame_flags()
 * except it takes the timestamp of the EOF, i.e. the timestamp of the end
 * of the last frame.
 */
int av_buffersrc_close(AVFilterContext *ctx, int64_t pts, unsigned flags);
```

So, in the former case, the EOF pts is manually specified (100); in the latter case, the pts is somehow inferred, wrongly: FFmpeg thought output frame 23 (92) would be the EOF, maybe because the last input frame fed in had pts 90? I'm not sure why it's inferred wrongly — that would entail digging even deeper into FFmpeg source. Anyway, I think it's reasonable to assume that `ffmpeg.c` decided to manually keep track of pts and use `av_buffersrc_close` for a reason. `av_buffersrc_close` wasn't really exposed in this crate, so I added a `close` method to `filter::Source` (f1ccd4e69641dbd2be98e3ef38e670b592a103c1) parallel to the `flush` method we were using.

That's the crucial change. Other major changes:

- `output_context.write_trailer()`, already mentioned;
- `encoder.flush`, metioned in my previous assessment, necessary in theory but doesn't affect behavior in this case.

I should also point out that `decoder.decode` and `encoder.encode` in fact rely on deprecated APIs (`avcodec_decode_video2` and `avcodec_encode_video2`). They should be replaced with `avcodec_send_packet`/`avcodec_receive_frame`/`avcodec_send_frame`/`avcodec_receive_frame`-based APIs, which don't exist in this crate yet; I should add those shortly, and once added those should be preferred.

---

Finally, since your actual program uses https://github.com/kornelski/rust-ffmpeg.git, you need to get in touch with kornelski in order to add the relevant API exposing `av_buffersrc_close` (or maybe he knows how to work around the `filter::Source::flush` frame-dropping problem).

**Comment by CL-Jeremy** [comment]
Thanks again for your kind and timely help. Not sure if you are already aware of this: http://ffmpeg.org/doxygen/4.0/group__lavc__decoding.html#ga3ac51525b7ad8bca4ced9f3446e96532

I had to add [this workaround](https://github.com/ImageOptim/gifski/commit/34a23c6c7ac142a4f6e6b4b8c3af57d5ac0ecdb7) to have it behave exactly as it should, just like using the FFmpeg CLI program. (Also note I'm using PTS + length for EOF. I suppose this matches what FFmpeg does).

It's actually the first time I've ever written anything in Rust. I'm sure it could be done in a more idiomatic way. I even went as far as trying to use raw pointers before I realized how bad that could be (for my purpose of overriding type guards and/or traits).

**Comment by zmwangx** [comment]
FFmpeg calculation of pts is in fact very complicated (pay attention to `ist->pts` and `ist->next_pts`):

- https://github.com/FFmpeg/FFmpeg/blob/n4.3.1/fftools/ffmpeg.c#L2321-L2452 Calculate pts largely from, but not limited to `best_effort_timestamp`;
- https://github.com/FFmpeg/FFmpeg/blob/n4.3.1/fftools/ffmpeg.c#L2553-L2635 Advance by `duration_pts` (which is scaled packet duration for the most part) in most branches.

It has all those branches and even heuristics because video codecs are very complex with packets coming out of order and not necessarily carrying pts info. (Compare to audio pts calculation, which is very simple.)

However, gif is nothing like H.264, H.265, AV1 and all that jazz. It's just a simple format with a series of crappily compressed frames... So I believe this is an anything-goes scenario.

**Comment by CL-Jeremy** [comment]
> However, gif is nothing like H.264, H.265, AV1 and all that jazz. It's just a simple format with a series of crappily compressed frames... So I believe this is an anything-goes scenario.

Yes, that pretty much sums up what I do there.

I was actually concentrating on the part where I need to feed empty packets to the decoder in order to get the remaining frames that are postponed for delayed decoding (which isn't applicable to all decoders/formats). This doesn't seem to apply to `avcodec_send_packet`/`avcodec_receive_frame`.

**Comment by zmwangx** [comment]
I should push a commit exposing the send/receive APIs some time soon (already sitting on my local branch but haven’t updated examples yet).
