### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by abhijeetbhagat** [zmwangx/rust-ffmpeg#7]
I am trying to build this on Windows. Can it be built on Windows? What are the steps?

**Comment by zmwangx** [comment]
Supposedly you should be able to use an FFmpeg build (e.g. a dev build from [here](https://ffmpeg.zeranoe.com/builds/)) in `FFMPEG_DIR` and get `ffmpeg-sys` to compile, then everything else follows. That is to say, in theory the steps are:

1. Download an FFmpeg build with the dev libs;
2. Set `FFMPEG_DIR` env var to where it's located;
3. `cargo build`.

Realistically, I tried it once about two years ago, and couldn't get my final binary to actually link to libav*. I gave up because I'm not a Windows developer and have no idea of how the linker works on Windows and how to fix it, especially in a rustc setting.

Might be worth another try I guess? But unfortunately I cannot offer any Windows help if you can't get it to work. Might need to ask around on IRC if you're determined. In any case, let me how it goes.

**Comment by zmwangx** [comment]
https://github.com/zmwangx/rust-ffmpeg-sys/blob/aaccc155d1dc0d21751a80d676fcf5d82075cdc7/build.rs#L535-L544

**Comment by abhijeetbhagat** [comment]
Yeah, that worked. Able to run the `codec_info.rs` code too. Before posting the issue, i went the `pkg-config` way creating `pc` files for all the FFMPEG libs and putting them in the right path. That didn't work though for some reason. Overlooked the `FFMPEG_DIR` part in `build.rs`. Thanks!

**Comment by zmwangx** [comment]
I didn’t even know pkg-config could run on Windows... Glad it’s working now, I should give it try myself some time. Btw, are you using a windows-msvc toolchain or a windows-gnu toolchain?

**Comment by abhijeetbhagat** [comment]
`pkg-config` comes with MSYS. I am using the gnu toolchain because my VC++ compiler (from VS 2013) is a bit old and the headers will not compile because it doesn't recognize the `inline` keyword.

**Comment by zmwangx** [comment]
Thanks for the info!
