### ISSUE TITLE
Need better docs on how to build

### ISSUE THREAD

**Issue by zmwangx** [zmwangx/rust-ffmpeg#9]

**Comment by abhijeetbhagat** [comment]
I can write a Windows guide. Please assign it to me if you/anyone isn't working on it already.

**Comment by zmwangx** [comment]
I’m not working on it and actually prefer to spend as little time as possible here, so yes please! You can use the wiki, I’ll eventually link to wiki articles from README.

**Comment by Boscop** [comment]
@abhijeetbhagat Yes, please! I need to build on Win 8.1 and 10 :)

**Comment by Boscop** [comment]
@zmwangx @abhijeetbhagat It tries to use pkg-config on Win 8.1:
> Compiling ffmpeg-sys-next v4.3.0 (D:\3rdparty\rust-ffmpeg-sys)
error: failed to run custom build command for `ffmpeg-sys-next v4.3.0 (D:\3rdparty\rust-ffmpeg-sys)`
Caused by:
  process didn't exit successfully: `D:\3rdparty\rust-ffmpeg\target\debug\build\ffmpeg-sys-next-1f41adb6c84bc303\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libavutil\"", cause: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." } }', D:\3rdparty\rust-ffmpeg-sys\build.rs:547:9

How can I make it work? :)

**Comment by abhijeetbhagat** [comment]
@Boscop , follow these steps:
1. Download the shared and dev versions of FFMPEG from https://ffmpeg.zeranoe.com/builds/
2. Unzip them somewhere.
3. Set an environment variable: `FFMPEG_DIR` with value /path/to/unzipped/dev/folder. This folder should contain `examples`, `include` and `lib` folders. Restart shell, if it is open, for it to see the newly created environment variable.
4. Try building.
5. If it builds fine, copy all the DLLs from /path/to/unzipped/shared/folder to the target/debug folder (where the executable resides). These DLLs contain the actual FFMPEG libraries implementation.
6. Try running.

I used the rust-gnu toolchain since i have an older VC++ compiler that comes with VS 2013. Since it doesn't recognize the `inline` keyword present in the FFMPEG headers, it fails. If you have a latest version of the compiler, then it may work.

What the build script does is check for the `FFMPEG_DIR` variable first and find the static libraries pointed by it. If it doesn't find it, then it tries to invoke the `pkg-config` tool. Since the `pkg-config` tool can't find where your static lib (.a) files reside, it fails.

Let me know what happens. Good luck!

**Comment by Boscop** [comment]
@abhijeetbhagat Thanks, I'll try it. And how can I link ffmpeg statically?

**Comment by Boscop** [comment]
```
   Compiling ffmpeg-sys-next v4.3.0 (D:\3rdparty\rust-ffmpeg-sys)
error: failed to run custom build command for `ffmpeg-sys-next v4.3.0 (D:\3rdpar
ty\rust-ffmpeg-sys)`

Caused by:
  process didn't exit successfully: `D:\3rdparty\rust-ffmpeg\target\debug\build\
ffmpeg-sys-next-57a35d9bed782d2c\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native="D:\3rdparty\ffmpeg-zeranoe\ffmpeg-4.3-win64-dev"
\lib
cargo:rustc-link-lib=dylib=avcodec
cargo:rustc-link-lib=dylib=avdevice
cargo:rustc-link-lib=dylib=avfilter
cargo:rustc-link-lib=dylib=avformat
cargo:rustc-link-lib=dylib=avutil
cargo:rustc-link-lib=dylib=swresample
cargo:rustc-link-lib=dylib=swscale
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
DEBUG = Some("true")
check.c
check.c(3): fatal error C1083: Cannot open include file: 'libavutil/avutil.h': N
o such file or directory

--- stderr
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
thread 'main' panicked at 'Compile failed', D:\3rdparty\rust-ffmpeg-sys\build.rs:407:9
```
It fails here:
https://github.com/zmwangx/rust-ffmpeg-sys/blob/89e5800682e1f5175464fa48148c5ffa3efc1a88/build.rs#L398-L408

This should be changed to use [`out_dir`](https://docs.rs/cc/1.0.54/cc/struct.Build.html#method.out_dir) instead of `current_dir` and `.file("check.c")` instead of `.arg("check.c")` and [`.compile(&executable)`](https://docs.rs/cc/1.0.54/cc/struct.Build.html#method.compile) instead of `.arg("-o").arg(&executable)`.

**Comment by abhijeetbhagat** [comment]
On Windows, we can't link directly with dynamic libraries (DLLs), but on Linux, we can. So on Windows, we either link with static libraries (those that contain the entire implementation) or with import libraries (static libraries that in turn 'point' to the dynamic libraries) when you build your program. By creating the `FFMPEG_DIR` environment variable, you tell the build script location of not only the FFMPEG static libraries (i.e., `libavcodec.dll.a` and others) but also the header files and so the build script will automatically link with the static libraries when you build.

**Comment by abhijeetbhagat** [comment]
@Boscop what is the value of the `FFMPEG_DIR` variable? I am hoping it is `D:\3rdparty\ffmpeg-zeranoe\ffmpeg-4.3-win64-dev`.

**Comment by Boscop** [comment]
Ah, the problem was the quotes around the path. Now it built successfully, thanks!

**Comment by Boscop** [comment]
@abhijeetbhagat Btw, I didn't mean to link to the dlls statically, but to link ffmpeg into my executable so that I don't need the dlls to execute my program.

**Comment by abhijeetbhagat** [comment]
@Boscop , yeah i understood what you want although, i am not sure why you would want to do that. Nonetheless, i think FFMPEG gives only import libraries and not full blown static libraries. Please correct me if i am wrong.

**Comment by Boscop** [comment]
@abhijeetbhagat Because it's much less convenient having to always remember to also copy the DLLs when I copy my exe to another computer (because then I first have to check in depwalker which dlls it needs and where they are, and it's easy to miss some, because it's not automatic).
So I prefer to link everything statically. Why wouldn't I want to do that?

Zeranoe has statically built ffmpeg.exe so shouldn't it be possible to also link to the ffmpeg lib statically like that exe does?

**Comment by abhijeetbhagat** [comment]
@Boscop if bundling the exe and its dependencies is a problem, then you can give https://github.com/volks73/cargo-wix a try (i myself haven't had an opportunity to try it though).

**Comment by mastfissh** [comment]
If you get errors about missing "libclang.dll", I found installing LLVM from https://releases.llvm.org/download.html and adding it to the PATH solved the problem.

**Comment by zmwangx** [comment]
One can also use libclang from Visual Studio, if the component is installed. See [this workflow](https://github.com/zmwangx/rust-ffmpeg/blob/b962e4f9f684167f5cd1556dd9768187be18644d/.github/workflows/build.yml#L81-L82) for an example. Useful for building in GitHub Actions at least. (`choco install llvm` takes forever.)

**Comment by DuckerMan** [comment]
![image](https://user-images.githubusercontent.com/23637939/93998686-8c137680-fd9d-11ea-80a9-1971ec410a35.png)

I've successfully compiled it with minGW!

**Comment by DuckerMan** [comment]
..and added a guide how to build it on windows with GNU toolchain

**Comment by zmwangx** [comment]
Late reply but thanks for the contribution. @DuckerMan 

I think I'm satisfied with what we have now (well I should add a brief paragraph about MSVC).
